categories: [Epigenetics]
description: This tool provide GO Enrichment Analysis of a gene set. Given a set of
  genes, this will return the enrichment GO categories after FDR control.
homepage_url: https://github.com/kpbioteam/clusterProfiler_go
name: clusterprofiler_go
owner: kpbioteam
remote_repository_url: https://github.com/kpbioteam/clusterProfiler_go
